### ISSUE TITLE
Pihole list missing?

### ISSUE THREAD

**Issue by pallebone** [arapurayil/aBL#6]
Hi there,

Thank you for your time and effort.

I was using your lists for quite a while with pihole. The list I used to be able to access was: 
https://raw.githubusercontent.com/arapurayil/ABL/master/lists/general/blocked_domains.txt

This list is now no longer available :( It just had domains only listed at one point. Is that gone forever now?
I had enjoyed using your lists in domain only format (required by pihole) until recently.

Kind regards
Peter

**Comment by arapurayil** [comment]
Hello Peter,

Thank you for letting me know that you found my list useful. :)

I decided to drop support for domain-only format as I found it to be less efeccient & flexible vis-à-vis ABP format. 
For instance, subdomains of `baddomain.com` can be easily blocked with `||baddomain.com^` instead of explicitly blocking `sub1.baddomain.com` , `sub2.baddomain.com`, etc. Besides ABP style DNS filtering can be extended by [modifiers](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#modifiers). 
As a result the list would be smaller but would block more 'bad' domains than the traditional domain-only list.

I hope you'd consider giving AdGuardHome a try with my new list.

**Comment by pallebone** [comment]
Hi @arapurayil,

Thank you for your reply. That makes sense, unfortunately I am locked into pihole now despite the benefits. I understand dropping support for domain only as you didnt use it yourself.

Thanks for running it in the past. I will look around for some other lists to make up for the loss :)

As you have fully answered my query the case can be closed.

Kind regards
Peter
